### ISSUE TITLE
Warning when using the OneTimePassEcto.Base.gen_totp with Elixir 1.8

### ISSUE THREAD

**Issue by chintan-mishra** [riverrun/one_time_pass_ecto#4]
The iex shell shows the following warning when using the library with Elixir 1.8 compiled using OTP 21.

```elixir
iex> OneTimePassEcto.Base.gen_totp(s, [{:token_length, 4}, {:interval_length, 300}])
warning: deprecated time unit: :seconds. A time unit should be :second, :millisecond, 
:microsecond, :nanosecond, or a positive integer
  (one_time_pass_ecto) lib/one_time_pass_ecto/base.ex:147: OneTimePassEcto.Base.interval_count/1
  (one_time_pass_ecto) lib/one_time_pass_ecto/base.ex:97: OneTimePassEcto.Base.gen_totp/2
  (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:258: :elixir.eval_forms/4
  (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
  (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
  (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
  (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
  (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
"8613"
```

**Comment by riverrun** [comment]
Fixed in #5
